<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="Checkout_Step1_YES_CS1_TC_40"
           tests="7"
           failures="3"
           errors="0"
           skipped="0"
           time="44.040">
  <properties />
            <testcase name="step05_clickOnSelectDateButton" time="5.123" classname="in.valtech.RoadScholar.test.CS1_TC_40">
                <failure type="java.lang.AssertionError"
                  message="expected [true] but found [false]"
              >
<![CDATA[java.lang.AssertionError: expected [true] but found [false]
  org.testng.Assert.fail(Assert.java:94)
  org.testng.Assert.failNotEquals(Assert.java:494)
  org.testng.Assert.assertTrue(Assert.java:42)
  org.testng.Assert.assertTrue(Assert.java:52)
  in.valtech.RoadScholar.pages.CheckOutStep1.<init>(CheckOutStep1.java:30)
  in.valtech.RoadScholar.pages.TripDatesAndPrices.clickOnSelectDateBtn(TripDatesAndPrices.java:55)
  in.valtech.RoadScholar.test.CS1_TC_40.step05_clickOnSelectDateButton(CS1_TC_40.java:78)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  java.lang.reflect.Method.invoke(Method.java:606)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
  org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
  org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
  org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
  org.testng.TestRunner.privateRun(TestRunner.java:767)
  org.testng.TestRunner.run(TestRunner.java:617)
  org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
  org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
  org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
  org.testng.SuiteRunner.run(SuiteRunner.java:240)
  org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
  org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
  org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
  org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
  org.testng.TestNG.run(TestNG.java:1057)
  org.testng.TestNG.privateMain(TestNG.java:1364)
  org.testng.TestNG.main(TestNG.java:1333)
]]>
      </failure>

          </testcase>
            <testcase name="step07_VerifyErrorMessage" time="0.015" classname="in.valtech.RoadScholar.test.CS1_TC_40">
                <failure type="java.lang.AssertionError"
                  message="expected [true] but found [false]"
              >
<![CDATA[java.lang.AssertionError: expected [true] but found [false]
  org.testng.Assert.fail(Assert.java:94)
  org.testng.Assert.failNotEquals(Assert.java:494)
  org.testng.Assert.assertTrue(Assert.java:42)
  org.testng.Assert.assertTrue(Assert.java:52)
  in.valtech.RoadScholar.pages.CheckOutStep1.<init>(CheckOutStep1.java:30)
  in.valtech.RoadScholar.test.CS1_TC_40.step07_VerifyErrorMessage(CS1_TC_40.java:104)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  java.lang.reflect.Method.invoke(Method.java:606)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
  org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
  org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
  org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
  org.testng.TestRunner.privateRun(TestRunner.java:767)
  org.testng.TestRunner.run(TestRunner.java:617)
  org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
  org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
  org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
  org.testng.SuiteRunner.run(SuiteRunner.java:240)
  org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
  org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
  org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
  org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
  org.testng.TestNG.run(TestNG.java:1057)
  org.testng.TestNG.privateMain(TestNG.java:1364)
  org.testng.TestNG.main(TestNG.java:1333)
]]>
      </failure>

          </testcase>
            <testcase name="step06_clickOnContinueButton" time="0.016" classname="in.valtech.RoadScholar.test.CS1_TC_40">
                <failure type="java.lang.AssertionError"
                  message="expected [true] but found [false]"
              >
<![CDATA[java.lang.AssertionError: expected [true] but found [false]
  org.testng.Assert.fail(Assert.java:94)
  org.testng.Assert.failNotEquals(Assert.java:494)
  org.testng.Assert.assertTrue(Assert.java:42)
  org.testng.Assert.assertTrue(Assert.java:52)
  in.valtech.RoadScholar.pages.CheckOutStep1.<init>(CheckOutStep1.java:30)
  in.valtech.RoadScholar.test.CS1_TC_40.step06_clickOnContinueButton(CS1_TC_40.java:91)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  java.lang.reflect.Method.invoke(Method.java:606)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
  org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
  org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
  org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
  org.testng.TestRunner.privateRun(TestRunner.java:767)
  org.testng.TestRunner.run(TestRunner.java:617)
  org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
  org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
  org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
  org.testng.SuiteRunner.run(SuiteRunner.java:240)
  org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
  org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
  org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
  org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
  org.testng.TestNG.run(TestNG.java:1057)
  org.testng.TestNG.privateMain(TestNG.java:1364)
  org.testng.TestNG.main(TestNG.java:1333)
]]>
      </failure>

          </testcase>
  
  
            <testcase name="step01_HomePage_URL" time="9.916" classname="in.valtech.RoadScholar.test.CS1_TC_40" />
                <testcase name="step04_clickOnDateAndPriceTab" time="6.267" classname="in.valtech.RoadScholar.test.CS1_TC_40" />
                <testcase name="step02_closeSignUpPopUp" time="10.102" classname="in.valtech.RoadScholar.test.CS1_TC_40" />
                <testcase name="step03_clickOnTripCardFromHomePage" time="12.601" classname="in.valtech.RoadScholar.test.CS1_TC_40" />
      
</testsuite>
